services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cakeshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_JWT_EXPIRATION: ${REFRESH_JWT_EXPIRATION}
      ACCESS_JWT_EXPIRATION: ${ACCESS_JWT_EXPIRATION}

volumes:
  postgres_data: